### PR TITLE
Closes #95: Modularizes application

### LINKED ISSUE #95: Modularize react native components
- [x] Separate components 
- [x] Create index.js and style.js for each component
- [ ] Create Utils folder for reusable functions

Example structure:

screen shot 2015-04-13 at 10 41 22 am

### PR DESCRIPTION
**Pull request by rkho**
- Moved ChatRoom.js into `app/views/ChatRoom`, renamed as `index.js`
- Created a `styles.js` file within the same folder, only imported necessary styling for the view
- Deleted unnecessary styling in the original styles.js file within `app/`

### CODE REVIEW

**Comment by arianf** [comment]
:-1: travis isn't happy with this...

**Comment by pravipati** [comment]
:+1: travis is now pleased with this

**Comment by pravipati** [comment]
l.g.t.m. :100:

**Comment by pravipati** [comment]
I think that this is a great start to modularizing our application into different components but I think there's more modularization to be done. Happy to let this merge close the issue for now, but I think we'll open up more modularization issues as our front-end grows.

**Comment by arianf** [comment]
@pravipati agreed.

**Pull request merged**
