### PR TITLE
Closes #70: Added Navigation Bar

### LINKED ISSUE #70: Navbar for Front-End
Implementing a navigation bar in the front-end

### PR DESCRIPTION
**Pull request by rkho**
Additionally, also modularized Views into their own folders.

### CODE REVIEW

**Comment by koziscool** [comment]
looks good in code.  pulled the latest commit on the branch.  Functionality looks good.

**Comment by rkho** [comment]
There's a bug in this version that causes the app to crash when sending a message from the application itself (but not through the SocietIO server). Do not merge until I fix.

**Comment by rkho** [comment]
Bug has been fixed. App was crashing when a message was being sent if the name field was not entered. Since that field is no longer necessary, I've removed it from the code.

**Comment by pravipati** [comment]
:+1:

**Comment by arianf** [comment]
:+1: nice

**Pull request merged**
