### PR TITLE
added npm install into installation script

### PR DESCRIPTION
**Pull request by arianf**

### CODE REVIEW

**Comment by rkho** [comment]
Love it!

**Comment by arianf** [comment]
Hold off on approving this until I give the okay.

**Comment by rkho** [comment]
sounds good

**Comment by arianf** [comment]
Okay, please review and merge.

**Comment by rkho** [comment]
This is

```
   ('-.     _   .-')      ('-.       .-') _               .-') _             
  ( OO ).-.( '.( OO )_   ( OO ).-.  (  OO) )             ( OO ) )            
  / . --. / ,--.   ,--.) / . --. /,(_)----.   ,-.-') ,--./ ,--,'  ,----.     
  | \-.  \  |   `.'   |  | \-.  \ |       |   |  |OO)|   \ |  |\ '  .-./-')  
.-'-'  |  | |         |.-'-'  |  |'--.   /    |  |  \|    \|  | )|  |_( O- ) 
 \| |_.'  | |  |'.'|  | \| |_.'  |(_/   /     |  |(_/|  .     |/ |  | .--, \ 
  |  .-.  | |  |   |  |  |  .-.  | /   /___  ,|  |_.'|  |\    | (|  | '. (_/ 
  |  | |  | |  |   |  |  |  | |  ||        |(_|  |   |  | \   |  |  '--'  |  
  `--' `--' `--'   `--'  `--' `--'`--------'  `--'   `--'  `--'   `------'   
```

**Comment by rkho** [comment]
This is outstanding.

**Comment by pravipati** [comment]
There's a console.log in the server.js -- please remove

**Comment by pravipati** [comment]
Please add newlines to all files.

**Comment by arianf** [comment]
done. :smile:

**Comment by pravipati** [comment]
:+1: Merging in now

**Pull request merged**
